name: profilias
description: "A new Profilias 2project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  # Flutter Core
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # State Management
  provider: ^6.1.5+1

  # Supabase
  supabase_flutter: ^2.12.0

  # Local Storage
  shared_preferences: ^2.5.4

  # Image Processing
  image_picker: ^1.2.1
  image: any
  flutter_image_compress: ^2.4.0
  file_picker: ^10.3.10
  timeago: ^3.7.1
  # UI Components
  material_symbols_icons: ^4.2906.0
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  fl_chart: ^1.1.1
  lottie: ^3.3.2


  cryptography: ^2.9.0
  record: ^6.1.2
  flutter_secure_storage: ^10.0.0

  # Internationalization
  intl: ^0.20.2

  # Utilities
  uuid: ^4.5.2
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  connectivity_plus: ^6.1.0  # Plus stable sur Windows Desktop
  rxdart: ^0.28.0
  url_launcher: ^6.3.2
  screenshot: ^3.0.0
  rename: ^3.1.0
  # Authentication
  google_sign_in: ^7.2.0
  faker: ^2.2.0
  http: ^1.6.0

  flutter_cache_manager: ^3.4.1

  # Database
  objectbox: ^5.2.0
  objectbox_flutter_libs: ^5.2.0

  google_mlkit_text_recognition: ^0.15.0

  csv: ^6.0.0
  pdf: ^3.11.3
  printing: ^5.14.2
  flutter_pdfview: ^1.4.4

dev_dependencies:
  # Testing
  flutter_test:
    sdk: flutter

  # App Launcher Icons
  flutter_launcher_icons: ^0.14.4

  # Code Generation
  objectbox_generator: ^5.2.0
  build_runner: ^2.10.5

  # Linting
  flutter_lints: ^6.0.0

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
